# Basic workflow I used a few days ago to deploy to google cloud run
name: Build and Deploy to Google Cloud Run

on:
  push:
    branches: [master]

env:
  PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  RUN_REGION: asia-east1
  SERVICE_NAME: avg-cweight-paginator

jobs:
  setup-build-deploy:
    name: The whole pipeline
    runs-on: [ubuntu-latest]
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
        with:
          version: '285.0.0'
          service_account_email: ${{ secrets.GCP_SERVICE_ACC_EMAIL }}
          service_account_key: ${{ secrets.GCP_SERVICE_ACC_KEY }}
          export_default_credentials: true
      - name: gcloud setup
        run: |
          gcloud config set project $PROJECT_ID
      - name: Build
        run: |
          gcloud builds submit -t gcr.io/$PROJECT_ID/$SERVICE_NAME:$GITHUB_SHA

      - name: Deploy
        run: |
          gcloud run deploy $SERVICE_NAME \
            --region $RUN_REGION \
            --image gcr.io/$PROJECT_ID/$SERVICE_NAME:$GITHUB_SHA \
            --platform managed \
            --set-env-vars DOMAIN=${{ secrets.DOMAIN }},INITIAL=${{ secrets.INITIAL }}
